# Generated by Django 3.1.4 on 2020-12-23 13:30

from django.db import migrations, models
import django.db.models.deletion
import month.models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0003_auto_20201221_0507'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(blank=True, max_length=50)),
                ('company_name', models.CharField(blank=True, max_length=75)),
                ('start_date', month.models.MonthField(blank=True)),
                ('end_date', month.models.MonthField(blank=True)),
                ('country', models.CharField(blank=True, max_length=60)),
                ('description', models.CharField(blank=True, max_length=300)),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resume.resume')),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_name', models.CharField(blank=True, max_length=20)),
                ('skill_level', models.CharField(choices=[('novice', 'Novice'), ('beginner', 'Beginner'), ('skillful', 'Skillful'), ('experienced', 'Experienced'), ('expert', 'Expert')], default='novice', max_length=11)),
                ('description', models.CharField(blank=True, max_length=50)),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resume.resume')),
            ],
        ),
    ]
