# Generated by Django 3.1.4 on 2020-12-24 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0004_skill_workdetails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='skill_level',
            field=models.CharField(choices=[('Novice', 'Novice'), ('Beginner', 'Beginner'), ('Skillful', 'Skillful'), ('Experienced', 'Experienced'), ('Expert', 'Expert')], default='novice', max_length=11),
        ),
    ]
